### ISSUE TITLE
The RealeseNote of module manifest are not update in build task

### ISSUE THREAD

**Issue by NicolasBn** [gaelcolas/Sampler#358]
### Problem description

The task 'Create_changelog_release_output' doesn't update the module manifest in build process.

You can see the problem in the module build with 0.112.1+ version of Sampler.

https://synedgy.visualstudio.com/Sampler/_build/results?buildId=1468&view=logs&j=bce26a94-9049-50eb-6c1c-385ccbec51f9&t=512e4b73-7a3e-57af-0534-ae809c1351da&l=137

the error message : `No valid manifest found for project '<moduleName>'. Cannot update the Release Notes.`

The problem came from the `-AsNewBuild` parameter added to `Set-SamplerTaskVariable` dot sourcing in task.
https://github.com/gaelcolas/Sampler/blob/a168b09f6fcdfe3192ca5dd333867f2fbc66ea8f/.build/tasks/release.module.build.ps1#L52

With this parameter, the `$builtModuleManifest` variable is not initiate. 

### Verbose logs

```text
No valid manifest found for project 'Sampler'. Cannot update the Release Notes.
```

### How to reproduce

Use 0.121.1+ version of Sampler in your pipeline 

### Expected behavior

Release Note are added in manifest.

### Current behavior

ReleaseNote are empty.

### Suggested solution

Moved the initialization of `$builtModuleManifest` outside of `-AsNewBuild` condition.

### Operating system the target node is running

```text
Windows 10
```

### PowerShell version and build the target node is running

```text
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module version used

```text
0.112.3
```

**Comment by DrIOSX** [comment]
I can confirm I'm experiencing this with the latest version of the sampler. I haven't found a good combination of previous modules in the requirements.psd1 allows it to work consistently. 

Any guidance on how to get versioning to work? Workarounds?

**Comment by johlju** [comment]
This problem seems that `-AsNewBuild` was added to this row when support for Choco packages was introduced

https://github.com/gaelcolas/Sampler/blob/d19ef072498ac9df81a3839b0b7a502a066f2235/.build/tasks/release.module.build.ps1#L50-L52

`-AsNewBuild` was only meant to be used for the build module task and then all other tasks should get the module version number from the module manifest. `AsNewBuild` should never been added to the above line, but removing `-AsNewBuild` from the above line will break Choco packages since they do not have a module manifest. 

We cannot just move the below initialization of `$BuiltModuleManifest` as suggested by @NicolasBn since `[Get-SamplerAbsolutePath.ps1](https://github.com/gaelcolas/Sampler/blob/main/Sampler/Public/Get-SamplerAbsolutePath.ps1)` returns the expected module manifest path regardless if it exist or not, thenthe task `Create_changelog_release_output` will try to modify a non-existent module manifest, also breaking Choco packages.

https://github.com/gaelcolas/Sampler/blob/d19ef072498ac9df81a3839b0b7a502a066f2235/Sampler/scripts/Set-SamplerTaskVariable.ps1#L153-L165

https://github.com/gaelcolas/Sampler/blob/d19ef072498ac9df81a3839b0b7a502a066f2235/Sampler/Public/Get-SamplerBuiltModuleManifest.ps1#L74-L76

We could workaround this move the above code, and change the `Get-SamplerBuiltModuleManifest` to return `$null` if the module manifest does not exist, to make sure the variable `$BuiltModuleManifest` is `$null` for Choco packages, and a valid path when it is a module package.

BUT, the best approach would be to remove  `AsNewBuild` that introduced the bug, and evaluate if it is a choco package, change this:
https://github.com/gaelcolas/Sampler/blob/d19ef072498ac9df81a3839b0b7a502a066f2235/Sampler/scripts/Set-SamplerTaskVariable.ps1#L113

to something like:

```powershell
 if ($AsNewBuild.IsPresent -or $IsChocoPackage) 
```

This change would be best so that all tasks always get the module version from the module manifest for module packages, and those packages that do not have module manifest get the version the same way as the build does, e.g. GitVersion.

**Comment by NicolasBn** [comment]
Is `$IsChocoPackage` already assigned in Sampler?

We need to found a way to implement it. Maybe in Build.yaml?

**Comment by johlju** [comment]
There is a lot of parameters in the Choco task, I'm hoping we could detect one of those in the current session by adding one of these choco parameters to the [release.module.build.ps1](https://github.com/gaelcolas/Sampler/blob/main/.build/tasks/release.module.build.ps1) ad that will be our "IsChocoPackage". 🙂 

https://github.com/gaelcolas/Sampler/blob/d19ef072498ac9df81a3839b0b7a502a066f2235/.build/tasks/ChocolateyPackage.build.ps1#L11-L58

For example if we would to add the following parameter to [release.module.build.ps1](https://github.com/gaelcolas/Sampler/blob/main/.build/tasks/release.module.build.ps1):

```powershell
$ChocolateyPackageId = (property ChocolateyPackageId '')
```

The it should give use either a package id or `*` in `$ChocolateyPackageId`, so then instead of this

https://github.com/gaelcolas/Sampler/blob/d19ef072498ac9df81a3839b0b7a502a066f2235/Sampler/scripts/Set-SamplerTaskVariable.ps1#L113

We should be able to do this:  
````powershell
$isChocoPackage = -not ([string]::IsNullOrEmpty($ChocolateyPackageId))

if ($AsNewBuild.IsPresent -or $isChocoPackage) 
```

But if that does not work, then we could look for the `

**Comment by johlju** [comment]
@gaelcolas was kind to make a test repo public https://github.com/SynEdgy/MyChocoPackage. Though Geal has not built it for a long time so it is not certain it works with current version of Sampler without some modifications.

**Comment by johlju** [comment]
So my theory in https://github.com/gaelcolas/Sampler/issues/358#issuecomment-1114924901 did not work since `Invoke-Build` runs all tasks and sets all default values so the parameter `$ChocolateyPackageId` will always contain `*` regardless if a task in that file has run or not. So I move to the backup plan and looking for a folder 'output/choco' that the parameter `$ChocolateyBuildOutput` holds.
